import type { NextPage } from "next";
import Head from "next/head";
// import CssNotification from "../components/utility-first/css-notification";
// import ResponsiveImage from "../components/responsive-design/media-responsive-image";
// import BreakpointResponsiveCard from "../components/responsive-design/media-responsive-card";
// import BreakpointColorTarget from "../components/responsive-design/media-responsive-button";
// import HoverButton from "../components/states/hover-button";
// import FocusInput from "../components/states/focus-input";
import DisabledButton from "../components/states/disabled-button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Tailwind App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <CssNotification /> */}
      {/* <ResponsiveImage /> */}
      {/* <BreakpointResponsiveCard /> */}
      {/* <BreakpointColorTarget /> */}
      {/* <HoverButton /> */}
      {/* <FocusInput /> */}
      <DisabledButton />
    </>
  );
};

export default Home;
